version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install for static HTML project."
  build:
    commands:
      - echo "Building static site..."
      - mkdir -p output
      - cp -r * output/
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'
  base-directory: output
