version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo Installing dependencies...
      - dotnet restore

  build:
    commands:
      - echo Building the application...
      - dotnet build --configuration Release
      - dotnet test --no-build --verbosity normal

  post_build:
    commands:
      - echo Publishing build artifacts...
      - dotnet publish src/MyApp -c Release -o ./publish

artifacts:
  files:
    - '**/*'
  base-directory: publish
